name: Homebrew

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string
    secrets:
      HOMEBREW_TAP_TOKEN:
        required: true

jobs:
  greeter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "mistydemeo/homebrew-cargodisttest"
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
      # So we have access to the formula
      - name: Fetch local artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: Formula/
      - name: Commit formula files
        run: |
          git config --global user.name "${GITHUB_USER}"
          git config --global user.email "${GITHUB_EMAIL}"

          for release in $(echo ${{ inputs.plan }} | jq --compact-output '.releases[]'); do
            name=$(echo "$release" | jq .app_name --raw-output)
            version=$(echo "$release" | jq .app_version --raw-output)

            git add Formula/${name}.rb
            git commit -m "${name} ${version}"
          done
          git push
